Fix some CTS failures
Fix CTS failures for the following:

1. I/0123456789ABCDEF: android.app.cts.SystemFeaturesTest#testSensorFeatures FAIL
junit.framework.AssertionFailedError: PackageManager#hasSystemFeature(android.hardware.sensor.light) returns false but SensorManager#getSensorList(5) shows sensors [TSL2550 Light sensor] expected:<false> but was:<true>

2. I/0123456789ABCDEF: android.app.cts.SystemFeaturesTest#testLiveWallpaperFeature FAIL
junit.framework.AssertionFailedError: PackageManager#hasSystemFeature should return true for android.software.live_wallpaper

3. I/0123456789ABCDEF: android.app.cts.SystemFeaturesTest#testScreenFeatures FAIL
junit.framework.AssertionFailedError
at android.app.cts.SystemFeaturesTest.testScreenFeatures(SystemFeaturesTest.java:207)

Included the required xml files in device.mk for 1 and 2
Created a new file android.hardware.screen.xml with the required screen properties for 3

Change-Id: I40bd5da92e5661b880cd05cd0a12a088b5c02ba3
Signed-off-by: Vishveshwar Bhat <vishveshwar.bhat@ti.com>